<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Module;
use Illuminate\Support\Str;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Module::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $moduleArray = [
            [
                "module_name" =>  "Dashboard",
                "module_type" => "frontend",
                "module_slug" => 'dashboard',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Profile",
                "module_type" => "frontend",
                "module_slug" => 'profile',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Manage Datasheets",
                "module_type" => "frontend",
                "module_slug" => 'frontend-datasheets',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Staff Member",
                "module_type" => "frontend",
                "module_slug" => 'staff',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Customer Support",
                "module_type" => "frontend",
                "module_slug" => 'customer-support',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Dashboard",
                "module_type" => "admin",
                "module_slug" => Str::slug('Dashboard', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Sub Admin Management",
                "module_type" => "admin",
                "module_slug" => 'sub-admin',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Customer Management",
                "module_type" => "admin",
                "module_slug" => 'customer',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Company Staff",
                "module_type" => "admin",
                "module_slug" => 'companystaff',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Manage DataSheets",
                "module_type" => "admin",
                "module_slug" => 'datasheet',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Backup Reports",
                "module_type" => "admin",
                "module_slug" => Str::slug('backup-report', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "City",
                "module_type" => "admin",
                "module_slug" => Str::slug('city', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "CMS Management",
                "module_type" => "admin",
                "module_slug" => Str::slug('CMS', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Manage Emission Factors",
                "module_type" => "admin",
                "module_slug" => Str::slug('Manage Emission Factors', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            // [
            //     "module_name" =>  "General Report",
            //     "module_type" => "admin",
            //     "module_slug" => Str::slug('General Report', '-'),
            //     "icon" => '',
            //     "status" => "1",
            //     "created_at" => date('Y-m-d H:i:s'),
            //     "updated_at" => date('Y-m-d H:i:s'),
            // ],
            
            [
                "module_name" =>  "Change Password",
                "module_type" => "frontend",
                "module_slug" => Str::slug('Change Password', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],

            [
                "module_name" =>  "Emission Factors",
                "module_type" => "admin",
                "module_slug" => Str::slug('emission-factors', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Well To Tank Fuels Management",
                "module_type" => "admin",
                "module_slug" => Str::slug('welltotankfuels', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Fuel Management",
                "module_type" => "admin",
                "module_slug" => Str::slug('fuels', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Vehicle Management",
                "module_type" => "admin",
                "module_slug" => Str::slug('vehicles', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Electricity Heat Cooling Management",
                "module_type" => "admin",
                "module_slug" => Str::slug('electricity-heat-cooling', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Transmission And Distribution Management",
                "module_type" => "admin",
                "module_slug" => 'transmission-and-distribution',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Water supply treatment Management",
                "module_type" => "admin",
                "module_slug" => 'water-supply-treatment',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Material Use Management",
                "module_type" => "admin",
                "module_slug" => 'material-use',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Waste Disposal Management",
                "module_type" => "admin",
                "module_slug" => 'waste-disposal',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Food Cosumption Management",
                "module_type" => "admin",
                "module_slug" => 'foodcosumption',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Business Travels",
                "module_type" => "admin",
                "module_slug" => 'bussinesstravel',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Employees Commuting",
                "module_type" => "admin",
                "module_slug" => 'employees-commuting',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Vans And Hgvs",
                "module_type" => "admin",
                "module_slug" => 'freighting-goodsgvh',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Flight, Rail, Sea Tenker And Cargo Ship",
                "module_type" => "admin",
                "module_slug" => 'freighting-goodsfr',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Profiles",
                "module_type" => "admin",
                "module_slug" => Str::slug('Profiles', '-'),
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Refrigerant Management",
                "module_type" => "admin",
                "module_slug" => 'refrigerants',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Contact Request Data Management",
                "module_type" => "admin",
                "module_slug" => 'contactus',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Backend Permission",
                "module_type" => "admin",
                "module_slug" => 'backend-permission',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                "module_name" =>  "Frontend Permission",
                "module_type" => "admin",
                "module_slug" => 'frontend-permission',
                "icon" => '',
                "status" => "1",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ]
        ];

        Module::insert($moduleArray);
    }
}
