<?php
return [
    'super_admin_email' => 'komal.cmarix@gmail.com',
    'emailPageUrl' => [
        'customerOnBoarding' => 'email.customer-on-boarding',
        'customerSupport' => 'email.customer-support',
        'CustomerCreateMail' => 'email.company-create-mail',
        'customerUpdateMail' => 'email.admin-company-update-mail',
        'subadmincreatemail' => 'email.accountCreated',
        'companydocument' => 'email.pending-document-email',
        'staffMemeberCreate'=> 'email.accountCreated',
        'datasheetProcessComplete'=> 'email.datasheet-complete-email',
    ],
    'emailSubject' => [
        'customerOnBoarding' => 'Successful Onboarding',
        'customerSupport' => 'Customer support - ',
        'CompanyAdminMail' => 'Company Create Mail',
        'CompanyAdminUpdateMail' => 'Admin Update Company Information',
        'SubAdminCreateMail' => 'Account Created',
        'CompanyPendingDocumentMail' => 'Company Pending Document',
        'StaffMemberCreateMail' => 'Account Created',
        'datasheetCalProcessComplete' => 'Activity Sheet Status',
    ],
    'scopeRules' => [
        'fuels' => ['2*3'],
        'refrigerants' => ['2*3'],
        // 'refrigerants' => ['2*2'],
        'wtt_fules' => ['3*3'],
        't_d' => ['2*2'],
        'material_use' => ['2*2'],
        'waste_disposal' => ['1*2'],
        // 'waste_disposel' => ['1*1'],
        'business_travel_land_and_sea' => ['4*4'],
        'employees_commuting' => ['4*4'],
        'food' => ['2*3'],
        'water' => ['2*2'], 
        'electricity_heat_cooling' => ['3*3'], 
        'owned_vehicles' => ['3*3' , '9*10'], 
        'freighting_goods' => ['3*3' , '9*10'],
        'home_office' => ['5*(6*160)*7*3*4*8'], 
        // 'flight_and_accommodation' => ['3*4'], // formula needed
    ],    
    'collumn'=> [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P'
    ],
    'perPageRecords' => 20,    
    'titleCollumnColor' => 'FF8496B0',
    'titleFontSize' => 11,
    'titleCollumnRowHeight' => 30,
    'valueCollumnColor' => 'FFD6DCE4',
    'valueFontSize' => 10,
    'titleFontColor'=> 'ff1f4e78',
    'typeWiseConsumptionHomeOffice'=>[
        'with_cooling' => 3.65,
        'with_heating' => 5.15,
        'no_heating_no_cooling' => 0.15,
    ],
    'countryWiseFactorsHomeOffice'=>[
        'United Arab Emirates' => 0.353309365289371,
    ],
    'otherCountryHotelFactors' => 57.8138506335977,
    'allowedDataSheetArray'=>[
        'Fuels', 
        'Refrigerants', 
        'Food', 
        'WTT-fules', 
        'T&D', 
        'Material use', 
        'Waste disposal', 
        'Business travel - land and sea', 
        'Employees commuting', 
        'Water', 
        'Electricity, heat, cooling', 
        'Freighting goods', 
        'Owned vehicles', 
        'Home Office', 
        'Flight and Accommodation',
    ],
    'tripType' => [
        'One Way' => 1,
        'Two Way' => 2,
    ],
    'distanceCategory' => [
        'shortHaul' => [
            'Economy Class' => 0.205359354362416,
            'Business Class' => 0.308032877852349,
        ],
        'longHaul' => [            
            'Economy Class' => 0.224718280536913,
            'Premium Economy Class' => 0.359525193288591,
            'Business Class' => 0.651656930201342,
            'First Class' => 0.898843029530201,            
        ],
    ],
    'mainReportTitleColor' => '333f4f',
    'columnBgColor' => 'a8d08d',
    'firstHorizontalTitleBgColor' => '3a3838',
    'reportDataBgColor' => 'e2efd9',

    'graphXYArray'=>[
        'Fuels'=> '0,4', 
        'Refrigerants' => '0,4', 
        'Food' =>'0,4',
        'WTT-fules' =>'0,4',
        'T&D' =>'0,3',
        'Material use' =>'0,3', 
        'Waste disposal' =>'1,3',
        'Business travel - land and sea' =>'0,5', 
        'Employees commuting' =>'0,5',
        'Water' =>'0,3',
        'Electricity, heat, cooling' =>'0,4', 
        'Freighting goods' =>[
            'vans' => '0,4',    
            'flights'=>'6,11'
        ],
        'Owned vehicles' =>[
            'passenger_vehicles'=>'0,4',
            'delivery_vehicles' => '6,10',
        ],
        'Home Office' =>'0,9',
        'Flight and Accommodation' =>[
            'flight'=>'2,4',
            'hotel' => '10,12'
        ],
    ],
    'newgraphXYArray'=>[
        'Fuels' => '0,1,4',
        'Refrigerants' => '0,1,4', 
        'Food' =>'0,2,4',
        'WTT-fules' =>'0,1,4',
        'T&D' =>'0,0,3',
        'Material use' =>'0,1,3', 
        'Waste disposal' =>'1,0,3',
        'Business travel - land and sea' =>'0,2,5', 
        'Employees commuting' =>'0,2,5',
        'Water' =>'0,0,3',
        'Electricity, heat, cooling' =>'0,4', 
        'Freighting goods' =>[
            'vans' => '0,2,4',    
            'flights'=>'6,7,10'
        ],
        'Owned vehicles' =>[
            'passenger_vehicles'=>'0,2,4',
            'delivery_vehicles' => '6,8,10',
        ],
        'Home Office' =>'0,1,9',
        'Flight and Accommodation' =>[
            'flight'=>'2,3,6',
            'hotel' => '10,8,11'
        ],
    ],
    'electricityType' => [
        'Electricity Grid', 
        'Heat and steam', 
        'District cooling',
    ],
    'homeCountry' =>[
        'Qatar',
        'Saudi Arabia',
        'United Arab Emirates'
    ],
    "country" => "Afghanistan,Åland Islands,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antarctica,Antigua and Barbuda,Argentina,Armenia,Aruba,Australia,Austria,Azerbaijan,Bahamas,Bahrain,Bangladesh,Barbados,Belarus,Belgium,Belize,Benin,Bermuda,Bhutan,Bolivia (Plurinational State of),Bonaire, Sint Eustatius and Saba,Bosnia and Herzegovina,Botswana,Bouvet Island,Brazil,British Indian Ocean Territory,British Virgin Islands,Brunei Darussalam,Bulgaria,Burkina Faso,Burundi,Cabo Verde,Cambodia,Cameroon,Canada,Cayman Islands,Central African Republic,Chad,Chile,China,China, Hong Kong Special Administrative Region,China, Macao Special Administrative Region,Christmas Island,Cocos (Keeling) Islands,Colombia,Comoros,Congo,Cook Islands,Costa Rica,Côte dIvoire,Croatia,Cuba,Curaçao,Cyprus,Czechia,Democratic Peoples Republic of Korea,Democratic Republic of the Congo,Denmark,Djibouti,Dominica,Dominican Republic,Ecuador,Egypt,El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia,Falkland Islands (Malvinas),Faroe Islands,Fiji,Finland,France,French Guiana,French Polynesia,French Southern Territories,Gabon,Gambia,Georgia,Germany,Ghana,Gibraltar,Greece,Greenland,Grenada,Guadeloupe,Guam,Guatemala,Guernsey,Guinea,Guinea-Bissau,Guyana,Haiti,Heard Island and McDonald Islands,Holy See,Honduras,Hungary,Iceland,India,Indonesia,Iran (Islamic Republic of),Iraq,Ireland,Isle of Man,Israel,Italy,Jamaica,Japan,Jersey,Jordan,Kazakhstan,Kenya,Kiribati,Kuwait,Kyrgyzstan,Lao Peoples Democratic Republic,Latvia,Lebanon,Lesotho,Liberia,Libya,Liechtenstein,Lithuania,Luxembourg,Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Martinique,Mauritania,Mauritius,Mayotte,Mexico,Micronesia (Federated States of),Monaco,Mongolia,Montenegro,Montserrat,Morocco,Mozambique,Myanmar,Namibia,Nauru,Nepal,Netherlands,New Caledonia,New Zealand,Nicaragua,Niger,Nigeria,Niue,Norfolk Island,North Macedonia,Northern Mariana Islands,Norway,Oman,Pakistan,Palau,Panama,Papua New Guinea,Paraguay,Peru,Philippines,Pitcairn,Poland,Portugal,Puerto Rico,Qatar,Republic of Korea,Republic of Moldova,Réunion,Romania,Russian Federation,Rwanda,Saint Barthélemy,Saint Helena,Saint Kitts and Nevis,Saint Lucia,Saint Martin (French Part),Saint Pierre and Miquelon,Saint Vincent and the Grenadines,Samoa,San Marino,Sao Tome and Principe,Sark,Saudi Arabia,Senegal,Serbia,Seychelles,Sierra Leone,Singapore,Sint Maarten (Dutch part),Slovakia,Slovenia,Solomon Islands,Somalia,South Africa,South Georgia and the South Sandwich Islands,South Sudan,Spain,Sri Lanka,State of Palestine,Sudan,Suriname,Svalbard and Jan Mayen Islands,Sweden,Switzerland,Syrian Arab Republic,Tajikistan,Thailand,Timor-Leste,Togo,Tokelau,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Turks and Caicos Islands,Tuvalu,Uganda,Ukraine,United Arab Emirates,United Kingdom of Great Britain and Northern Ireland,United Republic of Tanzania,United States Minor Outlying Islands,United States of America,United States Virgin Islands,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Wallis and Futuna Islands,Western Sahara,Yemen,Zambia,Zimbabwe"
];